### ISSUE TITLE
Error Initializing MCP2515

### ISSUE THREAD

**Issue by KKChand** [johnmholmes/YouTube-Can-Arduino-Nano#2]
I am using  can_send.ino to see some output on serial monitor... I am using Arduino mega 2560 and MCP2515
I see this error: can you please help me how to fix this.

13:00:20.400 -> Entering Configuration Mode Failure...
13:00:20.400 -> Error Initializing MCP2515..

**Comment by johnmholmes** [comment]
I have not tried using a Mega 2560 but that should work as long as you get the correct pins setup for the MCP2515 module. can you confirm the pins you have used for the CAN module?

**Comment by KKChand** [comment]
![image](https://github.com/johnmholmes/YouTube-Can-Arduino-Nano/assets/102440540/3ebcd214-e52f-46cd-9d0d-e5e2a23c7fba)
same as shown here. I didn't connect int pin. I have used jumper J1 for 120ohms terimination

**Comment by KKChand** [comment]
with UNO R3 it is working fine.

18:54:31.622 -> Setting Baudrate Successful!
18:54:31.622 -> MCP2515 Initialized Successfully!
18:54:31.622 -> Message Sent: on
18:54:36.594 -> Message Sent: of
18:54:41.612 -> Message Sent: on
18:54:46.628 -> Message Sent: of
18:54:51.615 -> Message Sent: on

**Comment by johnmholmes** [comment]
Hi thanks for the feed back the Uno and the Nano use the same SPI pins so it works fine but on the Mega we need to alter the jumper wires to suit that board, and amend the sketch to reflex these particular pins.

![Screenshot 2024-04-08 021538](https://github.com/johnmholmes/YouTube-Can-Arduino-Nano/assets/60571002/b93b9e96-0e7b-4569-be00-6262122e28c8)

this shows the different pin configurations required

**Comment by johnmholmes** [comment]
Closed ref that the sketch needs to be changed due to the Arduino Mega using different pins to communicate with the MCP2515

**Comment by johnmholmes** [comment]
no issue with original documentation

**Comment by KKChand** [comment]
Thanks, it is working now with Mega2560.

**Comment by johnmholmes** [comment]
Thanks for the feedback it is always great to hear  people are able to use  the examples share.
